### ISSUE TITLE
0.8.2 preview available, has selective paste bug fix and Lightroom crash fix

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#119]
https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.8.2

* Bug fix: paste selected parameters now working. See [Set Options Dialog](https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog) on the wiki for revised instructions for use.
* Camera Profile selections added (Adobe Standard, Clear, Deep, Landscape, Light, Neutral, Portrait, Standard, Vivid).
* In the application, menu items that are alread mapped to a control will be highlighted in red.
* Added Vignette to lens corrections.
* Added ability to toggle profile corrections and turn on/off automatic lateral chromatic abberation correction.

Please post an issue if you have problems--particularly you Mac folks. I double checked permissions, so it shouldn't be a problem this time.

**Comment by rsjaffe** [comment]
I have just reloaded the version with a proposed fix for the Lightroom crash bug. If you downloaded it earlier, please replace with the newer version.

**Comment by krakozavr** [comment]
still crashing when MIDI re-scanning. Do you need a logs?

**Comment by rsjaffe** [comment]
Yes. The MIDI re-scanning issue is different. And I'm still not sure what's causing it, since we can't reproduce it. Please send logs. Also, please send me a list of all tasks running on your machine when the crash occurs. [See here for instructions on printing out a task list](http://helpdeskgeek.com/windows-xp-tips/save-a-list-of-running-processes-to-a-text-file-in-windows/).

**Comment by krakozavr** [comment]
you will see the loooooong list of chrome.exe - don't pay attention because I reproduced this crash without the google chrome launched (BTW, I had restarted my system before this experiment especially to have as clean system as possible), and I run it after to check some instructions about the tasklist. Also, I reproduced this error without control panel /event viewer and total commander; these apps wal loaded just to collect logs more comfortable (and without the Total Commander it was impossible at all because all linked files disappeared as soon as the error windows is closed).

[errorlog.zip](https://github.com/rsjaffe/MIDI2LR/files/73712/errorlog.zip)

**Comment by rsjaffe** [comment]
This appears to be a bug in the application framework used for the app. See the wiki FAQ for further information
