### ISSUE TITLE
Only Tint and Temp are kept different TIFF/DNG

### ISSUE THREAD

**Issue by PhantomLordM** [rsjaffe/MIDI2LR#122]
Hello,

I'm using custom limits for Temperature, Tint, Exposure, Contrast, Saturation and Clarity while working on TIFF and DNG files. From what I understand those limits should be allowed to be set differently for TIFF and differently for DNG. However from what I see, only Temperature and Tint limits are kept different while the rest are always as were set last time, no matter if file is TIFF or DNG.

I'm not sure if that's a bug or I misinterpreted the feature.

**Comment by rsjaffe** [comment]
The limits are different **only** when the ranges are different. Lightroom determines, for each picture, what the appropriate ranges are for each control--I assume that's based upon raw vs. non-raw and bit depth. It may also be based on other factors.

In short, it sounds like the limits feature is functioning as designed. 

I can't find any method in the LR SDK to get the photo's type (or extension). Even if I could, changing limits by file type would be quite complicated.

**Comment by rsjaffe** [comment]
I've poked around a little, and found that at least the following are available ranges, depending upon the quality of the file. Note that png, tiff, jpg and dng files all can have different ranges--the file extension only tells part of the story.

Ranges I've found with some of my files:

| Parameter | DNG  | PNG TIFF JPG | PNG TIFF JPG | HDR DNG made by LR |
| -------- | :------: | :-------: | :----------: | :------------: |
| Temperature | 2000 50000 | -100 100 | -100 100 | 2000 50000 |
| Tint | -150 150 | -100 100 | -100 100 | -150 150 |
| Exposure | -5 5 | -4 4 | -5 5 | -10 10 |
| Contrast | -100 100 | -50 100 | -100 100 | -100 100 |
| Saturation | -100 100 | -100 100 | -100 100 | -100 100 |
| Clarity | -100 100 | -100 100 | -100 100 | -100 100 |

So, clarity and saturation limits will be the same in all these situations.

Contrast will as well (because MIDI2LR only looks at the upper end of the range to see if the limits should apply). I'm a bit surprised by contrast having a range change only at the lower end, but will not change the program's behavior unless this becomes a big issue, as I may then have to track down the behaviors for all of the possible controls.

Some PNG/TIFF/JPG files have different ranges than other PNG/TIFF/JPG files, so the range will depend upon the file. Same with DNG files, as the high bit-depth DNGs produced by LR's merge to HDR have a wider exposure range.

**Comment by rsjaffe** [comment]
I've added this information to the wiki.

**Comment by Polekso** [comment]
Thank you it's good to know that.
