### ISSUE TITLE
First beta release for profile changes is now available

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#130]
Currently only compiled for Windows machines. I'll try to get a Mac version up soon. Read the wiki sections https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Profiles and https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog carefully before using this feature. Comments and feedback welcome.

https://github.com/rsjaffe/MIDI2LR/releases

**Comment by OzzyDevil69** [comment]
Hi as i'm new to this i really wanna say your doing a great job... I can't wait for the mac version :)

**Comment by krakozavr** [comment]
Hi!
I'm a little bit confused.
I saved the profile with the new name brush.xml
I printed the profile's name in the Options -> Profiles -> Brush Adjustments field.
Now, when I pick the BRUSH tool, the new brush.xml profile is loading, wow! :)
But:
1. When I drop the brush off, nothing happen - my default profile isn't loaded back, the BRUSH.XML still active;
2. I can't use this profile because all available actions are the default ones; so, I can load the new tools-related profile but I can't add any tools-related controls.

**Comment by rsjaffe** [comment]
That is the expected behavior if profiles aren't set for other Develop panels and tools. See the third paragraph in the **Cautions** section in https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Profiles for a discussion of how to avoid that problem.

**Comment by Polekso** [comment]
Hi! don't really get how works the "select a profile" Do I have to name each profile by the name of "profileX.xml" to call it? Thank you.

**Comment by rsjaffe** [comment]
Any name you want. You have to then type that name in the box in the profile options dialog.

**Comment by Polekso** [comment]
It works very fine! thanks! it's very useful.
Do you know if it's possible to let the light on on a button (bfc2000) as I can see on witch profile I am.
Like in the "encoder groups"
Do you think It's possible by modifying the .syx? 
Thank you
