### ISSUE TITLE
WACOM tablet

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#135]
very strange issue. My Wacom (Intuos 3) doesn't working in the MIDI2LR application. I can't set mapping :) 

Prpbably not a big deal, but I have no mouse now :)

**Comment by rsjaffe** [comment]
That is weird. Let me get this straight--you are using the Wacom instead of a mouse, and the MIDI2LR application is ignoring your attempts to click on buttons in the application? Might want to check if the JUCE framework is having that issue, as we're not doing anything special with mouse input--just using the JUCE application framework.

**Comment by krakozavr** [comment]
yest, it's true. I van drag the MIDI2LR's window (but it is a general windows operation), but I can't do anything inside. Cursor is moving around, and I can see trails when I pressing the buttons on the pen (analog of the right-click) but nothing more. With the latest 0.9.2 version, I have the same issue.

**Comment by rsjaffe** [comment]
Looks like there's been some requests for support, but nothing so far... http://www.juce.com/forum/topic/graphic-tablet/wacom-tablet-support

Can you use the tablet in a mouse emulation mode?

**Comment by StevenKersting** [comment]
I'm able to use my Intuos5 wireless w/ the Midi2LR app.

**Comment by rsjaffe** [comment]
MIDI2LR depends upon the correct interactions of four different software programs (LR, the plugin, the app, the hardware device driver) and the hardware. To compound that, we are using many diffent types of hardware. I'm afraid that this issue is way beyond my resources to identify and fix. If you ever identify a solution, please send it my way.

**Comment by krakozavr** [comment]
yes, I tried the mouse mode. It's terrible :) but as turnaround to make changes in the MIDI2LR it's work :)
