### ISSUE TITLE
Selected bouton on BCF2000

### ISSUE THREAD

**Issue by Polekso** [rsjaffe/MIDI2LR#153]
Hello,
Although I did not participate much in the conversations I'm still here to watch closely the advanced software .
From my side I test and retest ever to find the ideal configuration.
The aim would soon produce a labeling my BCF2000 with all the options I use.
After many configuration tested it seems to me that it would be interesting to use the pavement ( store / Learn / edit / exit ) in order to assign each a profile.
each button would have a color that corresponds to this action has on the control surface . 
This way.
![couvbfc2000_assign](https://cloud.githubusercontent.com/assets/16288796/12509796/56eefe7c-c105-11e5-8f29-a6e655d4909f.gif)

What I would like in this configuration is that the light stays on the pavement when using each profile (red, yellow , green, blue )
This way it would be easy to read on the control surface.
Do you think this is possible ? 
Thank you

**Comment by Polekso** [comment]
Is any one have an idea about that?

**Comment by rsjaffe** [comment]
It's possible, but kind of complicated. You'll have to reprogram the MIDI controller to use those as control change (CC) buttons instead of store,learn, edit, exit functions. The setup in MIDI2LR.zip under *Controller_Settings/BCF2000 RSJ OneProfile* does just that. 

But that's only the first step. Then we'll have to send CC codes  from the app to the buttons. We can do that, but we haven't implemented it for buttons yet, only knobs and faders.

Also, you may or may not be able to map those buttons to commands. I don't know how the app will handle that.
