### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by bozwellox** [rsjaffe/MIDI2LR#159]
I'm in the process of giving MIDI2LR a whirl as it's becoming more and more apparent that Paddy is no longer being supported. So far, so good, but I have a few feature requests:

1. Support for keyboards/game controllers, specifically the Logitech G13. I used this with Paddy and it is perfect for quickly applying presets, navigating, copying & pasting etc. 

2. The ability to assign a midi button to the "toggle all panels" function.

3. Likewise for the "toggle lights out" function. With both of these in Paddy I was able to hit two keys and see the image in full screen with no other distractions - heaven!

4. I can't find the ability to map a midi button to the "paste previous" function, only paste and paste selected. Am I being blind, or is it not available?

I have no idea how feasible these are, but they are just a few things that are holding me back from finally making the switch from Paddy to MIDI2LR, and ditching Lightroom 5.7!

Thanks for all the effort put in to creating this plugin - much appreciated.

Paul

**Comment by rsjaffe** [comment]
See the bottom of https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Photo-Actions for an explanation of how copy/paste works. You can paste all settings or paste only selected settings.

By toggle all panels, are you referring to "hide" panels?

--as to lights out--I have to look into that.

MIDI2LR doesn't currently support keyboards, but if someone is interested in writing the code for that, it would be welcomed. I don't have the bandwidth right now to attempt that, but this is an open source project, and anyone can contribute.

**Comment by bozwellox** [comment]
Hi Rory,

I get the options for pasting, but one of the standard pasting options in Lightroom is "paste settings from previous" I use that quite often when working through a series of similar images.

As for the panels thing - yes, that's what I meant, so all panels close (maximising the amount of space for the image on screen). Really nice when used in conjunction with lights out mode.

Hoping someone with greater coding skills than me can work something out with keyboard support, it really adds another level of customisation.

**Comment by losinternet** [comment]
I have been messing around with the code and have come up with an easy way to send keyboard shortcuts.  The downside is that the routine is for Windows only.  The cool thing about this is that you can map your ALT, CTRL, etc keys to be toggled on with the MIDI controller - kinda how you use the caps lock, and if your midi controller has leds you can knokw they are on.  



I too also have a Logitech G13, however I just map the Logitech G13 keys to keyboard shortcuts through the logitech software.  The Logitech supports 3 profiles, so I have one set for culling/reviewing, 1 for editing shortcuts and 1 for brush/pphotoshop settings.  I really havent had a need to map the logitech to MIDI commands, since Lightrooms shortcuts are already very good for my needs.   I think the real power of the midi controller is the ability to adjust the sliders.  I use a BCR2000 for this.

**Comment by bozwellox** [comment]
@losinternet That sounds interesting! Is this available to test out?

**Comment by losinternet** [comment]
Soon. Just need to find time to put something that is user friendly together. 
I have stuff hard coded into the application and will need to move that to the xml input file to make it adjustable for everyday use.   But when it's done there is the potential to use your midi controller buttons to send any number of key combinations, even outside of Lightroom.

**Comment by bozwellox** [comment]
Great stuff - good work!

Let me know if you need anyone to help out with testing, I'd be glad to get stuck in.

**Comment by bozwellox** [comment]
Great stuff - good work!

Let me know if you need anyone to help out with testing, I'd be glad to get
stuck in.

**Comment by losinternet** [comment]
Ok, I have something that seems to work, but I will need to integrate it in with the code and need to add the ability to use the GUI to set up the keyword shortcuts.  
I am at a loss about how to contribute to the project, rather than just grabbing the code and doing my own mods, but it is something Ill look into.

Right now I can add keyboard macros and shortcuts and assign these to any midi button.  The shortcuts appear in the GUI, but to add them you need to edit the XML file.

So far I kept the early structure, but here is a quick explanation:
1.  Working on windows only.  I dont have a Mac for testing, and the underlying code is windows specific
2.  You can assign an infinite number of keystrokes, or key combinations to a single MIDI key
3. These do not require any lightroom connection, just the midi2lr app.  So you could just use the midi2lr and your midi controller to send any number of key combinations.
4. The "toggle on" feature to hold down an ALT, CTRL or whatever key is coming soon

Here are two examples on how to use it, once I find a way to upload it:
`<setting keyboard_shortcut="1" channel="1" NRPN="False" Relative="False" controller="109" command_string="@0x44,0x11+0x32,0x4c,0x49,0x11+0x12+0x10+0x4f"/>
  <setting keyboard_shortcut="1" channel="1" NRPN="False" Relative="False" controller="110" command_string="@0xDC"/>  `

The addition of the keyboard_shortcut="1" tells identifies the code as sending keyboard command.
The actual keyboard shortcuts are stored after command_string="@"  The keys are stored in hex value for now.  For example 0x41 is the A key 0x11 is CTRL.  Keycodes can be found here [https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396](url)

Using a + means hold the key down and using a , means release the key.  So breaking down the first example this is what we get when we push the MIDI button 109 on channel 1:
`0x44,0x11+0x32,0x4c,0x49,0x11+0x12+0x10+0x4f`
We have 5 commands (separated by commas) for 1 button push.  These are 

D (develop module) then
CTRL+2 (Toggle the Tone Panel) then
L (Lights out) then
I (photo info) then
CTRL+ALT+SHIFT+O (open the photo overlay dialog)

The other example just toggles the \ key for before and after (0xDC is the \ key)

**Comment by rsjaffe** [comment]
git is a tool for distributed editing on a project, and github is a specific hosting service for projects. Github also provides a github for windows that you might find easiest to work with (I did). Download github for windows, sign up with github, then "clone" the project. You can then do edits and create a pull request. I'll review the pull request and, if I approve the request, git will integrate your changes into the project.

**Comment by losinternet** [comment]
Thx.
Ill give it a shot and hope to be able to contribute something useful.

**Comment by rsjaffe** [comment]
We may want to run powershell scripts instead. For example, the following script sends F1 to Lightroom:

```
[void] [System.Reflection.Assembly]::LoadWithPartialName("'Microsoft.VisualBasic")
[Microsoft.VisualBasic.Interaction]::AppActivate("Lightroom")

[void] [System.Reflection.Assembly]::LoadWithPartialName("'System.Windows.Forms")
[System.Windows.Forms.SendKeys]::SendWait("L")
```
I'm leaning towards that approach because it should be easy to replicate in OSX using its scripting capabilities.

**Comment by losinternet** [comment]
Ok. Not a problem 

FYI. For the Windows I was just using the sendinput() command available through the windows.h header.

**Comment by rsjaffe** [comment]
See #189 for a windows alpha test version of the app, and https://github.com/rsjaffe/MIDI2LR/blob/feature-send-keys/Source/LR_IPC_Out.cpp for the relevant code.
