### ISSUE TITLE
Alpha test: sending keystrokes to Lightroom: Windows and OS X!

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#191]
See the following for warnings and a copy of the plugin and programs:

https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.6KeysAlpha

OS X testers particularly needed.

**Comment by sherwood69** [comment]
Please add Before\After (key \).

**Comment by rsjaffe** [comment]
If you have a PC, the following file has the new executable with the \ added. *Before/After* in the Miscellaneous menu. Just unzip into your MIDI2LR.lrplugin directory.

[MIDI2LR.zip](https://github.com/rsjaffe/MIDI2LR/files/135688/MIDI2LR.zip)

**Comment by sherwood69** [comment]
Hello!
Yes, i have a PC.
Sorry to say it, but it looks like you have programmed wrong key (win-key) INSTEAD of "\" key. :(
When i bind a button to this func and press it - my start menu opens only but nothing else. 


>Среда, 17 февраля 2016, 21:19 -08:00 от rsjaffe <notifications@github.com>:
>
>If you have a PC, the following file has the new executabl with the \ added.  Before/After in the Miscellaneous menu. Just unzip into your MIDI2LR.lrplugin directory.
>MIDI2LR.zip
>—
>Reply to this email directly or  view it on GitHub .


-- 
Artem Gusev

**Comment by bozwellox** [comment]
Thanks for adding this Rory. I've just got round to installing it and overall it seems to work like a charm. I've noticed a couple of issues though, and have a couple of requests:

1. Contrast adjustment seems broken - moving the slider up and then down often results in contrast continuing to increase. Subsequently, moving any other slider afterwards (e.g. one mapped to exposure, shadows, whatever) continues to adjust contrast until you click into a different panel or change to another photo.

2. This might just be my BCF2000 but the 8 rotary controllers at the top, some of them seem to share the same midi CC, so if I open the Midi2LR panel and push one of them in and assign a function, the push in function of the next rotary controller seems to be assigned to the same CC, so it shares the same function I assigned to the previous controller. If that makes any sense...

3. It doesn't seem possible to assign a button to the targeted adjustment for either curves or HSL. I use this a lot in Paddy - hit the button, click on an area of the image and drag up/down to adjust - I love that feature.

4. One thing Paddy has, which I only spotted recently is "toggle mode", which seems to be good when used in conjunction with for example the store, learn or edit buttons (i.e. where the red LED illuminates). I use this for a toggle between normal view and "hide all panels", and also for....

5. "High sensitivity mode" - this is something Paddy has, which again I assign to a "toggle" button (and is a perfect example of when that is handy). I hit the store button, it goes into high sensitivity mode for finer adjustments (which affects all sliders and rotary controllers, with the sliders resetting to 0). Whilst in this mode the red LED is illuminated. When done, hit the store button again, the LED goes out and it returns to normal sensitivity mode.

6. It would be nice to have the option to have an on screen message box appear briefly when moving sliders (and to be able to configure where the message appears on screen), confirming what is being changed and showing the increase/decrease values, and to disappear once you've stopped moving the slider. This is especially handy when working in lights out mode. 

7. Now that we have keystroke functionality, would it be possible to open things up so we can add our own options rather than choosing from the pre-defined list? Not a big issue, and I see that this keeps things simpler to use but, for example, I wanted to change the "cycle lights out" option, which is using hte keyboard shortcut L, to shift + L, which reverses the cycling (so you go from lights on, to lights out, to dimmed). I prefer that as it's just one button press to go into lights out mode rather than two. There will probably be other things like that which weird people like me have found and like to use.

I think that's it! Apologies if this isn't the most efficient way of logging these kind of things.

Thanks again to everyone involved for all your efforts - it's much appreciated.

**Comment by bozwellox** [comment]
I've just spotted that someone else posted about the contrast issue and it was reported as fixed, so I checked my version and although it said v.0.9.7 in the plugin manager, the Midi2LR app itself showed v0.9.6 somehow. So, I disabled it, closed LR and deleted the folder, then re-downloaded v0.9.7 and installed again. It's now showing as 0.9.7 in both the plugin manager and on the app, but now I've lost the keystrokes functionality.

So I'm confused. Have I installed the wrong version? Is there a version that includes the keystrokes and the fix for the contrast issue?

I did spot that for some reason the "remove" button is greyed out in the plugin manager (for all plugins, not just Midi2LR), so I wonder if that is what caused the wonky version. Any ideas why it's greyed out, and how to fix it?

**Comment by rsjaffe** [comment]
The keystrokes version is experimental and doesn't include the latest fixes in the main version. I'll update the keystrokes version soon and pull in the main version's fixes. The version number in the experimental version shows which main version it is based on.

> This might just be my BCF2000 but the 8 rotary controllers at the top, some of them seem to share the same midi CC

Check the programming of your BCF2000. I bet they're not programmed correctly.

> It doesn't seem possible to assign a button to the targeted adjustment for either curves or HSL. I use this a lot in Paddy - hit the button, click on an area of the image and drag up/down to adjust 

Haven't seen how to do this yet. If anyone has more info on how to do this, would be glad to put it in.

> One thing Paddy has, which I only spotted recently is "toggle mode", 

Not sure what that is. Have to have more info to be able to see whether this can be done.

> "High sensitivity mode" - this is something Paddy has, which again I assign to a "toggle" button (and is a perfect example of when that is handy).

Working on something like this, but will be several releases before I try it.

> It would be nice to have the option to have an on screen message box appear briefly when moving sliders (and to be able to configure where the message appears on screen), confirming what is being changed and showing the increase/decrease values, and to disappear once you've stopped moving the slider.

That's present in the latest versions: https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog#show-status-and-activity

> Now that we have keystroke functionality, would it be possible to open things up so we can add our own options rather than choosing from the pre-defined list?

That's going to require some retooling of the app, which is why I've hesitated to do that. In the meantime, you can just send me requests of keystrokes to add. Now that the whole thing is database driven, it's very easy to add things. I went to a database-driven model because we have over 500 commands in this thing. See Database.lua for the database. I then have a module (documentation.lua) that churns out some of the necessary C++ code, lua tables, and wiki documentation.

**Comment by bozwellox** [comment]
Thanks Rory, you are surely "da man". Or something.

I'll try and explain the toggle mode thing when I'm at my PC and less drunk.

Cheers!

Paul

**Comment by sherwood69** [comment]
Hello, Rory!

Have you seen my message? can you check this please? the only thing i am using out of my controller now is \ key on my pc keyboard to preview before-after. In your last compilation with keystrokes that you sent me the \ key not working correctly, it opens up a start menu (equal to win-key) but not sending any \ key to LR.

>Четверг, 18 февраля 2016, 12:26 +03:00 от Artem Gusev <djdisc@list.ru>:
>
>Hello!
>Yes, i have a PC.
>Sorry to say it, but it looks like you have programmed wrong key (win-key) INSTEAD of "\" key. :(
>When i bind a button to this func and press it - my start menu opens only but nothing else. 
>
>
>>Среда, 17 февраля 2016, 21:19 -08:00 от rsjaffe < notifications@github.com >:
>>
>>If you have a PC, the following file has the new executabl with the \ added.  Before/After in the Miscellaneous menu. Just unzip into your MIDI2LR.lrplugin directory.
>>MIDI2LR.zip
>>—
>>Reply to this email directly or  view it on GitHub .
>
>
>-- 
>Artem Gusev


-- 
Artem Gusev

**Comment by rsjaffe** [comment]
Yes, I see that. I manually changed the code to make sure it was sending a \ to LR and it was, and I'm still getting the behavior you described. Don't know how to fix that yet. Help from others on this issue is welcome.

**Comment by rsjaffe** [comment]
Well, now I know what is happening. Turns out that the Juce Keypress class isn't very good at returning the proper keycodes. This is why sending keys to LR from MIDI2LR has stayed in alpha--I suspected it was going to be difficult. Anyway, download the following zip and extract the application into your plugin folder. I've tested it and it works on my machine (Windows 10).

[MIDI2LR.zip](https://github.com/rsjaffe/MIDI2LR/files/139281/MIDI2LR.zip)

**Comment by rsjaffe** [comment]
By the way, fixing this in general is going to take a bit of time--I'm going to continue work and *not* release a general beta for a while.

**Comment by sherwood69** [comment]
Thank you very much. It works like a charm now! I hope it will be released someday. I will try to help with testing as much as i can:)


>Суббота, 20 февраля 2016, 10:20 -08:00 от rsjaffe <notifications@github.com>:
>
>Well, now I know what is happening. Turns out that the Juce Keypress class isn't very good at returning the proper keycodes. This is why sending keys to LR from MIDI2LR has stayed in alpha--I suspected it was going to be difficult. Anyway, download the following zip and extract the application into your plugin folder. I've tested it and it works on my machine (Windows 10).
>MIDI2LR.zip
>—
>Reply to this email directly or  view it on GitHub .


-- 
Artem Gusev
