### ISSUE TITLE
Version 0.9.8 preview available

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#197]
Now with send keys! See the release notes for details. I still need OS X testers to check functionality of send keys in that operating system. Until it is verified, send keys functionality is turned off by default for OS X users. Information on how to turn it on and test it is in the release notes. 

https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.8

**Comment by mclaren777** [comment]
I just wanted to say that I my Korg nanoKONTROL2 arrived today so I'm finally able to try MIDI2LR. Setup worked perfectly with v0.9.8 and I'm currently running OSX 10.9.5, though I plan to eventually use this utility on a Windows 7 machine.

If I have time, I would love to test out send keys for you, but right now I'm focused on finding a way to decrease the delay between a slider movement and when Lightroom accepts the input and writes to the History panel. Using a MIDI controller is (so far) much slower than my old G13 setup because I have to wait for an adjustment to "bake" before moving another slider.

Is there a way to speed things up in this regard?

**Comment by bozwellox** [comment]
Keystrokes seem to be working nicely (Windows 10), but I'm still getting some very funky behaviour when adjusting contrast with a slider - big delay in the slider moving, sometimes it increases when I'm trying to do the opposite, editing contrast in general seems very broken). I have also set "reset contrast" to a button, and instead of resetting it seems to increase/decrease the amount, depending on which direction you moved the slider in previously, in small increments.

Aside from that all seems to be working beautifully aside from general slowness, but that might be down to my old laptop.

I should be receiving a Behringer X-Control mini in a few days so I will set that up and test also.

**Comment by rsjaffe** [comment]
> If I have time, I would love to test out send keys for you, but right now I'm focused on finding a way to decrease the delay between a slider movement and when Lightroom accepts the input and writes to the History panel. Using a MIDI controller is (so far) much slower than my old G13 setup because I have to wait for an adjustment to "bake" before moving another slider.

> Is there a way to speed things up in this regard?

Yes: LrDevelopController.setTrackingDelay( seconds ). Sets the number of seconds that tracking remains enabled after each adjustment is made. It's normally two seconds. 

Near the bottom of Client.lua is the line:
```lua
LrDevelopController.revealAdjustedControls( true ) -- reveal affected parameter in panel track
```
You can add the line directly after that with your desired tracking delay (note this may increase the number of history lines recorded, which is why tracking delay is normally set so high). For example, to reduce the delay to 0.5 seconds, add the line
```lua
LrDevelopController.setTrackingDelay( 0.5 )
```

**Comment by StevenKersting** [comment]
I'll try the OSX version in the next couple of days...

**Comment by rsjaffe** [comment]
@bozwellox see #198 for resolution of the contrast slider issue--it's a LR bug again. I'm giving up on the patch I put in place to fix another LR bug that fails to reveal the basic adjustments panel when Contrast slider is moved.

**Comment by rsjaffe** [comment]
New version released https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.8
