### ISSUE TITLE
"Paste from Previous" action not working

### ISSUE THREAD

**Issue by AlePhoto** [rsjaffe/MIDI2LR#200]
I am the only one? paste from previous, copy settings, paste settings seems not working :( HELP PLEASE! all the rest seems working, a big round of applause to the developer, great work so far!

**Comment by StevenKersting** [comment]
Can't duplicate in 9.8 on OSX

**Comment by AlePhoto** [comment]
I own a Windows7 macchine e LR6! forgot to mention it

**Comment by StevenKersting** [comment]
Have you set the "paste selections" options?

**Comment by AlePhoto** [comment]
If I push "copy" via midi controller the windows dialog box doesn't pop up...

**Comment by rsjaffe** [comment]
Correct. Copy/paste in MIDI2LR uses a different method. 
Copy: copies all settings and adjustments from current photo.
Paste: pastes all settings and adjustments that were last copied.
Paste selective: pastes the settings set in the [Paste Selections portion of the plugin's options dialog](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#paste-selections). If you check "Ask each time" in the paste selections tab, it will pop up each time you paste. Otherwise, you set it once, and use it as much as you want.

**Comment by AlePhoto** [comment]
thanks this helped me a lot! any thought why "paste previous" doesn't seem working? and... last but not least.. what about and "auto Sync" button? doesn't seem exist, right? thanks!!!

**Comment by emkorec** [comment]
If keystrokes works well (soon I guess), you will have an easier job I think. Copy prompt with dialog is Ctrl + Shift + C, paste is Ctrl + Shift + V. Paste from Previous is Ctrl + Alt + V

**Comment by AlePhoto** [comment]
rsjaffe said "I won't be adding keystroke commands that duplicate commands already in MIDI2LR, as the commands already in the program directly interact with Lightroom" ... I have updated to last version but still having this issue. Am I alone? could you check for me rsjaffe? please :) I am on windows as I said before.

**Comment by AlePhoto** [comment]
the issue is "past from previous" not working

**Comment by rsjaffe** [comment]
Traveling. I'll look into it when I have a chance.

Paste from previous is a keystroke command, not one of the command already in MIDI2LR. Are others able to use it successfully?

**Comment by AlePhoto** [comment]
ok understood. yes, the others seems fine. thanks!

**Comment by AlePhoto** [comment]
Hi rsjaffe, have you had the time for check the "past from previous" issue? the problem persist. I'm testing it even with bcf2000 and x touch mini.. please help

**Comment by rsjaffe** [comment]
The key assignment looks correct. I'll have to debug some more.

**Comment by AlePhoto** [comment]
thanks you :) .... but does it work for you? It seems I'am the only one bumped into this issue.

**Comment by bozwellox** [comment]
I'm also having this problem with "paste from previous" not working. Mac 10.11.3, Lightroom CC 2015.5, Midi2LR version 0.9.9.

**Comment by rsjaffe** [comment]
Which language keyboard are you using? Adobe assigns different keystroke shortcuts for different keyboards.

Also, I'm reworking the key-sending code, so this hopefully will be fixed soon.

**Comment by bozwellox** [comment]
It's a standard UK Macbook Pro keyboard. The standard keyboard shortcut is Command + Alt(option) + V. This works perfectly if you use the keyboard shortcut, but not when using a button assigned to that function within Midi2LR.

Regarding the key code, would it be possible to open it up so we can assign our own keyboard combinations to a key, rather than choosing from a list?

Thanks.

**Comment by rsjaffe** [comment]
Yes, that's what I'm working on.

**Comment by bozwellox** [comment]
Great stuff, thanks!

**Comment by rsjaffe** [comment]
See #31

**Comment by Natladia** [comment]
Hi! The way I found to solve "copy and past" was it:
In Lightroom choose File> Plugin Extras> Options.
In the new tab choose Other.
In first shortcut, check: ctrl + shift and write C in the blank field after.
In the second shortcut, check: ctrl + shift and write V in the blank field after.
Click on Ok.
Now go to MIDI2LR tab. Select the button for copy.
Select "Keyboard shortcuts for user" and choose "Key 1"
Repeat the process for paste.
Ready!
