### ISSUE TITLE
New Release: Customizable keyboard shortcuts

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#227]
https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.10

Main change is customizable keyboard shortcuts. [See the wiki for details](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#other-settings). Note that keyboard shortcuts are still experimental for OS X--I haven't received enough feedback to be confident that it all works.

**Comment by stevejmu** [comment]
I like the new options for Keyboard Shortcuts. A few things I noticed about release 0.9.10:

1. The version number still says 0.9.9 and I received a prompt stating the a new version 0.9.10 was available, so that's confusing. This happened on a fresh install of MIDI2LR, where I downloaded 0.9.10 from the latest release page.

2. The Keyboard Shortcuts seem to be mapping to something different than what's the key that's assigned. For example, I used the letter 'W' to map Key 1, but then it played a slideshow. I also tried mapping CTRL+SHIFT+S to a keyboard shortcut, but it brings up the secondary display window. I wonder if it's because the developer has a different keyboard language assigned during development or if it's just bugs in the code.

Keep up the great work!

**Comment by stiliajohny** [comment]
Hi all, 

I am using a nanoKontrol2 controller, Lightroom CC Clasic Desktop Based on MacOS High Sierra
When I assign the Shift+Ctrl+L command in one of the keys and I execute it the Plugin crashes. 

Any idea?

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
