### ISSUE TITLE
develop modules not working

### ISSUE THREAD

**Issue by pjkemp** [rsjaffe/MIDI2LR#235]
Instructions: Please type on the blank lines below each heading (### identifies the headings), and include the information requested under "System Information". Delete these instructions when done. If you are submitting a feature request or comment, delete everything and just start writing. Thanks.
 
click on develop module function (basic, tone curve, HSL,etc) ribbon expands. do work in that function

clicking on develop module function (Lens Corrections) opens ribbon and auto scrolls back to basic. Cannot manipulate second function actions since focus immediately returns to basic function....

### System information

* Operating system (Windows 10 ) and version:
* MIDI2LR version:9.10.1
* Lightroom version:CC 2015.5 [ 1067055 ]
* Lightroom language:EN
* Keyboard language:EN
* MIDI controller:KORG nanoKONTROL2
* Plugin installation directory:h:\picture_vault\plugins
* Profiles save directory:

**Comment by rsjaffe** [comment]
Which commands were you using?

Do you have different profiles assigned?

**Comment by pjkemp** [comment]
I just tried things with your plugin disabled. Things worked fine.

 

Try this…

 

Set up a mobile sync for the photo.

 

Go to develop module

Make a change in the basic panel

 

Now try and use any other panel in the develop module.

 

You should see the basic panel take focus away from where you were. 

 

It looks like the history thinks that ‘camera raw settings’ are being changed.

 

Attached is the profile file …

 

Let me know how I can help further…

 

PK

**Comment by rsjaffe** [comment]
OK, I tried that with a photo I have in a collection synced with Lightroom Mobile. I edited exposure, then dehaze. I did not see the behavior you did, until I did them quickly enough so that the history hadn't been updated between the two. I don't think I can fix this completely, as this is a Lightroom behavior causing the problem. 

However, what you can do is open up the MIDI2LR options dialog, select the Other... tab, and reduce that Tracking Delay. That will speed up Lightroom updates. Tracking delay is number of seconds between last adjustment and time LR records them in history. It looks like the history recording is what causes the problem. So if the delay is short enough, Lightroom will record the history for the basic module adjustment before you start the other adjustment, and you shouldn't have the issue. Just note that that will increase the number of history entries in your file. Try this and reply if this fixes the problem or not.

**Comment by pjkemp** [comment]
I have version 0.9.10.1 and cannot find the other tab anywhere. All I have are ‘Load’ ‘Save’ and ‘Settings’ amd in settings there are no tabs?

 

Am I missing something?

 

Thanks

PK

**Comment by rsjaffe** [comment]
Yes. [Read this section of the wiki.](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog)

**Comment by pjkemp** [comment]
No luck. Dropped the value to .6 and still getting behavior. Can’t understand why this just started happening… It used to work just fine..

**Comment by pjkemp** [comment]
I tried disabling GPU support and things started working normally…

 

FYI

 

(I am running an NVIDIA GTX 760)
