### ISSUE TITLE
X-Touch Mini not updating when moving between photos

### ISSUE THREAD

**Issue by bozwellox** [rsjaffe/MIDI2LR#237]
### Expected behavior

I was expecting the values (and therefore the LEDs on the rotary controllers) to update when switching between photos, e.g. if shadows are increased on one photo, the LEDs display that and when I switch to the next (unedited) photo, for the LEDs to reset to zero (and any movements of the rotary controller to start from zero) OR from whatever value the develop sliders are set to (in the case where you move to a photo with adjustments already applied).

### Actual behavior

The LEDs remain in their previous state, i.e. still displaying what the last adjusted value was for each encoder, and if I adjust something it frequently doesn't do anything at first - the pop-up value box which I've enabled shows two values, one with a minus in front of it. In order to adjust the value I have to firstly swing the encoder PAST one of the values displayed, then swing the other way to get it where I want it to be. It's hard to describe, but simply put I can't just move to a photo and decrease the shadows/adjust the crop without first swinging to an extreme value in the other direction. Then it picks up and I can adjust the value using the rotary controller.

### Steps to reproduce the behavior

It seems to happen on every photo (Canon RAW), but to explain my usual process - I select an image, apply a preset (using the controller), or paste a previously copied setting, then make adjustments. It is when making adjustments that it seems like it is "stuck" with previous settings, and I need to swing the controller past a certain value (in the other direction) before I can adjust in the direction I want, e.g. I want to adjust the exposure with a negative adjustment but in order to do so I first need to wildly adjust the exposure with a positive adjustment, THEN I'm able to decrease the exposure with the controller.

Sorry for the waffle, just trying to explain the weird behaviour!

### System information

* Operating system (Windows or OS X) and version: OSX 10.11.3
* MIDI2LR version: 0.9.10 - latest version available as of now
* Lightroom version: CC 2015.5
* Lightroom language: English
* Keyboard language: UK
* MIDI controller: X-Touch Mini (also have a BCF-2000 but I've not tested Midi2LR with it yet)
* Plugin installation directory: Within Preferences folder
* Profiles save directory: Documents folder

**Comment by bozwellox** [comment]
P.S. Pickup mode is enabled in the Midi2LR settings.

**Comment by rsjaffe** [comment]
When you see two boxes with two different numbers, that means you're in pickup mode and the controller is not tracking LR--the value that is steady is the LR value, and when you move the other value past the LR value you get "picked up".

Could you try the following: adjust exposure with a knob on your controller, then, without touching any other controls or buttons on your controller, use you mouse to adjust exposure on Lightroom. Do the lights track that change? When you go back to the controller, is it in sync or do you have the two boxes showing up again on Lightroom?

Does it only get out of sync when you apply a preset? Are you applying the preset through MIDI2LR or directly in LR?

Are you switching layers on the X-Touch Mini? When switching layers, the controller loses track of things, because of a limitation with the way layers on the controller are managed. The controller ignores all signals meant for the hidden layer, so it is often out of sync when you change layers. I could set up a "refresh" command, but that would mean assigning a controller button to that, which is kind of a waste. The software has no way of knowing when a layer is switched.

As you can see, this is kind of complicated, so we'll have to try a number of things--ideally, I'd like to be able to reproduce this problem on my machine, or else I'm just guessing when I try to make a fix for it.

**Comment by bozwellox** [comment]
Sorry for taking ages to update this. Over the last couple of evenings I've moved from the X-Touh Mini to the BCF2000 (first time using it with Midi2LR on the Mac) and, in a nutshell, Lightroom/Midi2LR is not playing nicely with either of my controllers. I'm pretty sure it must be down to my setup (perhaps because my midi devices had both been set up to work with PFixer before moving to Midi2LR), and so my next step will be to try and find factory default settings for both controllers and reset before asking you to look into this any further.

The problems are most apparent on the BCF2000. I can open a photo with everything at default (zero) settings, make changes, then when I switch to the next photo the sliders don't move. Everything stays the same as the last photo.

Give me a few days and I'll start from scratch - like I say, it must be something funky about my used and abused controllers. Almost everything is working (I just editing about 400 photos this evening), but the sliders don't do "the jumpy thing" when moving between photos - they stay in the same position and I have to make wild changes in any direction to force it to pick up.

I think I've broken it.

**Comment by bozwellox** [comment]
P.S. As difficult as this might be to believe, I'm not a simpleton. I had Midi2LR working perfectly with the same BCF2000 on my old PC. It's since I've moved to the dark (Mac) side my problems have started, but during the Mac move I also fiddled with the setup of the BCF2000 to make it work with PFixer, so I think it's something to do with that.

If anyone has a factory settings file for the BCF2000 please get in touch - I'm struggling to find it!

**Comment by rsjaffe** [comment]
**Panic Reset** for BCF2000. This function resets the most important MIDI data to their facotry settings.

1. Press EDIT and keep it pressed.
1. Now press EXIT. The reset is performed as soon as you press EXIT. "PAnC" (for "Panic") appears in the display.
1. As soon as the reset is over, your B-CONTROL goes automatically into the play mode, and the current preset is shown in the display.

**Comment by bozwellox** [comment]
Reinstalled Midi2LR and reset the BCF2000. Now all updating correctly! I'll check the X-Touch Mini again later. Thanks.
