### ISSUE TITLE
Adjustment lag/freeze when using Midi

### ISSUE THREAD

**Issue by zachter** [rsjaffe/MIDI2LR#250]
### Expected behavior
Move dial for exposure, temperature, tint, etc and it react to moving

### Actual behavior
Occasionally the controller stops responding completely, takes a few seconds till the sliders in lightroom move again.

On my x-touch mini when i switch from layer a to layer b and back it stops responding to any adjustments.

### Steps to reproduce the behavior
Just color correcting in general it happens every few images.

### System information

* Operating system (Windows or OS X) and version: Yosemite, also occasionally happens on my PC Windows 10
* MIDI2LR version: Latest
* Lightroom version: Lightroom CC
* MIDI controller:Behringer X-Touch Mini

### Additional comments
This tends to happen mostly on the MacbookPro which has 16gb of Ram and 2.7ghz processor. Occasionally it will freeze up on my PC as well (Windows10, 32gb Ram, SLI-GTX 760's, 3.5GHz Processor)

If there are any fixes or reasons why this may be happening let me know.

**Comment by emkorec** [comment]
Same here with OSX El Capitan, latest MIDI2LR, Lightroom CC, controller: Behringer X-Touch Compact

**Comment by rsjaffe** [comment]
See first issue in https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues to see if that addresses the problem.

Also, turn on [Show Status and Activity](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#show-status-and-activity) in the plugin options dialog. Normally, you should see one set of numbers displayed while moving the controller. Do you see two sets when it freezes? If so, then the controller has become out of sync with the application, and it is waiting in pickup mode for you to move your control near to the current picture's settings.

**Comment by zachter** [comment]
For some reason Showing the status and activity seemed to have fixed the problem with the dials not working. Is there a way to move where the status and activity bar shows? It shows right on top of the picture and I'd like to move it

**Comment by zachter** [comment]
So 2 sets of numbers do show up. How do I stop that from happening?

**Comment by rsjaffe** [comment]
Two sets of numbers show up when your slider or knob is out of sync with Lightroom's settings. Could you describe to me the exact set of steps to replicate that issue? I suspect it's the way your controller switches modes. We may have to add a "total refresh" button to MIDI2LR or find a way for your controller to signal MIDI2LR when it does a mode change.

**Comment by zachter** [comment]
So I use an x-touch mini. It has a Layer A and Layer B button to so you can have multiple functions for each button and knob. One set on A and another on B. I have all of my exposure, temp, highlights, blacks and what not on layer A, then I have the Tone curve on layer B, along with some luminance, vibrance, and saturation. So I'll adjust the exposure and temp and what not, then switch to layer b to adjust different contrast and color adjustments. When I switch from A to B the knobs become unresponsive until I rescan MIDI or i twist the knob back and forth a ton then it registers.

When I switch from A to B for binding commands MIDI2LR show a different number for layer A and Layer B fo reach button and knob. So Knob 1 on Layer A is CC:1 and on Layer B it 's CC:11. So it seems like it recognizes I'm on a different layer but doesn't resync with lightroom on it's on on each layer.

**Comment by rsjaffe** [comment]
Thanks for the clear description. Here's what's happening:

#### How MIDI2LR works with the controller

MIDI2LR knows of all the knob and button assignments you have, but doesn't know which ones are active in a particular layer.

It also assumes that your controller remembers the last setting it was at. For example, if knob for exposure is on layer A, it assumes that the controller will remember knob A's value.

And it assumes that, when it sends an updated value to the MIDI controller, the controller responds appropriately.

#### How this becomes a problem

When you switch layers, the MIDI controller does not remember the values from a prior layer. So, when you switch from A → B → A, the prior settings for the A knobs are lost by the controller. This means that the knob is out of sync with MIDI2LR, and won't work until you turn it past the current photo's settings ("pickup mode")--this is so that you won't have massive unexpected changes caused by the knob being out of sync.

Also, when you are in layer B, MIDI2LR is sending back information on what has changed on layer A, but your controller is ignoring it. MIDI2LR doesn't know that.

Finally, a layer switch could trigger MIDI2LR to do a full update, but I don't know if the x-touch mini could be programmed to send a notification when layers change. If it doesn't send a notification, MIDI2LR has no idea that it needs to do an update.

#### Potential solutions

If the x-touch mini can send a notification when changing layers, this problem can be easily solved, by mapping the notification to a "full update". Does the x-touch mini have this capability?

If not, we'll have to add a "full update" command to MIDI2LR, and you'll have to click the button associated with that command to cause an update.
