### ISSUE TITLE
Allow different sizes for presets listing in dialog box

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#321]
See https://groups.google.com/forum/#!topic/midi2lr/7BS9zwWLu1c

Currently it is 4X10, but a mac user with a large screen needed 8X5 as it appears the mac doesn't allow one to scroll to the later tabs (10 tabs in 4X10, not all displayed at once).

**Comment by rsjaffe** [comment]
Testing shows that making this 8X5 for all results in a dialog box that is too tall for most screens, so will have to make this an option to set.

**Comment by nop25751** [comment]
I'm having the same issue.

Suggestion: Wouldn't it be better to have the name Develop Preset on top of the tabs and on each tab just have the associated number (1-4; 1-8 and so on). This would make the name on the tab smaller and more easy to access and read.

Also would be nice to have this all panel to enlarge and shrink since on a 13'' Mac one cannot access the OK and Cancel buttons as they are not visible because there is no room to move the panel around in order to show them.

THANK YOU for this wonderful app and keep up the excellent work.

Kind regards,

Rui M Leal


P.S: - Attach is an image to what I'm reporting.

**Comment by jkanz** [comment]
![image](https://user-images.githubusercontent.com/32303812/30868971-00141d08-a2ae-11e7-8d73-9b2f931e9771.png)
Here is a screenshot of the issue mentioned above. Presets 33-40 can not be accessed by mac users.
Here is a temporary fix for the issue
1. In Lightroom, go to File -> Plug-in Extras -> Export Presets
2. Any presets you have selected are displayed in the resulting text file
![image](https://user-images.githubusercontent.com/32303812/30869632-a791f388-a2af-11e7-9e88-185380bace65.png)
3. In order to set presets 33-40, you may paste the preset IDs after the last ID in the list (make sure they are formatted correctly) Save the text file.
4. In Lightroom, go to File -> Plug-in Extras -> Load Presets.
5. In Lightroom, Check under File -> Plug-in Extras -> Options. Verify that your desired presets are saved.

**Comment by Dgrewer** [comment]
Hi, please remove me from the thread. Thanks!

Mvh Fredrik
