### ISSUE TITLE
Paste selected settings: temp and tint

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#355]
Need to check whether these are properly pasted. If not track down bug.

**Comment by mathieucarbou** [comment]
Confirmed - this is a bug. Values are not pasted through the paste selection dialog.

**Comment by mathieucarbou** [comment]
Wow it's more than that... If we select only Temp, Tint (w/o ProcessVersion), it does not work.
But if I click on `Basic Tone`, all values get pasted correctly.
So it's just individual pasting of these 2 items that does not work. Just pasting only Exposure for example works fine.

**Comment by mathieucarbou** [comment]
Note: I am wondering if LR behavior changed and we now need to surrond the setvalue by `LrTasks.startAsyncTask`, like I needed to do for #332 

```
+    LrTasks.startAsyncTask ( function ()
 +      if Ut.execFOM(LrDevelopController.getValue, param) == 0 then
 +        LrDevelopController.setValue(param,1)
 +      else
 +        LrDevelopController.setValue(param,0)
 +      end
 +    end )
```

**Comment by rsjaffe** [comment]
Basic Tone pastes more values than Temp, Tint, so I don't think it is the async task issue. I'd look at the values that are set by Basic Tone vs those set by Temp, Tint. Basic Tone may include some hidden values.

**Comment by mathieucarbou** [comment]
I would be interested in knowing how you can extract the values set by whole section Id. You are using a Lightroom command for that ?

**Comment by mathieucarbou** [comment]
@rsjaffe : I found the issue in debug mode. Glad to made it work :-)

So the issue is in ClientUtilities.lua around line 152:

```
      local TargetSettings = LrApplication.activeCatalog():getTargetPhoto():getDevelopSettings() 
      for _,param in ipairs(ParamList.SelectivePasteIteration) do 
        if (ProgramPreferences.PasteList[param] and MIDI2LR.Copied_Settings[param]~=nil) then
          TargetSettings[param] = MIDI2LR.Copied_Settings[param]
        end
      end
```

Suppose you are copying the Temp. and Tint of an image set to let's say a `Custom` WB. Then, you go to the next image, which has its WB set to `As Shot`.

So when the dev settings are applied, Temp and Tint values gets copied correctly. The thing is that for these parameters, we also need to run before:

`TargetSettings['WhiteBalance']='Custom'`

Otherwise, the values are ignored.

To verify that, if we also select White Balance in the Paste Selection screen, all works fine.

So there's a workaround right now, but generally speaking, MIDI2LR would need to have somewhere an indication of what are the parameters to copy or set when some are copied. For example, I think it would be best to remove Temp. and Tint from the screen and only keep White Balance. Because what you copy usually is not these parameters but their combination, which is the WB.

Simplifying that, it would mean that MIDI2lR needs to know somewhere that when WS is selected, the developper settings that needs to be copied are `Temperature`, `Tint` and `Whitebalance`.

**Comment by rsjaffe** [comment]
I'm in favor of keeping the dialog as it is, and adding custom white balance to the target settings when either tint or temperature is selected. I'll patch ClientUtilities.lua with a fix.

**Comment by rsjaffe** [comment]
I'm adding this right before withWriteAccessDo

      if (TargetSettings.Tint or TargetSettings.Temperature) then
        TargetSettings.WhiteBalance = 'Custom'
      end

**Comment by mathieucarbou** [comment]
Hi @rsjaffe : didn't have time to test this week-end, but this is what I did in debug mode and it works.
