### ISSUE TITLE
Akai LPD8 Pad's are not correctly stored

### ISSUE THREAD

**Issue by Jewest** [rsjaffe/MIDI2LR#43]
Akai LPD8 Pad's are not correctly stored.
I installed the plug in and configured the pad1 to pad8, no dials were configured.
Saved the file under akai(no extension?)
rebooted Lightroom 6.2, and midi controller did not work.
opened the config screen again and when I pressed the Pad 1 a new entry was made.
The configuration options are blocked(next/previous and reject) in the new settings

**Comment by rsjaffe** [comment]
Were the control numbers for the pads changed? The behavior you're describing would occur when the MIDI control panel is using a different profile from the one used when originally setting it up with MIDI2LR. MIDI2LR works by assigning an action to a given control number, which is why the previously configured options are blocked.

**Comment by Jewest** [comment]
I checked and it seems to work now.
please close this item, I will report again once I found out how I can reproduce it.
sorry for wasting your time.
