### ISSUE TITLE
LRcopy and LRpaste commands do not work since introduction

### ISSUE THREAD

**Issue by t-r-u** [rsjaffe/MIDI2LR#445]
LRcopy and LRpaste commands do not work since introduction on all different versions of Midi2Lr. It simply does nothing when I press the assigned buttons on the controller. However the previous commands "Settings Copy & Paste" worked without an issue in the earlier versions of the plugin.

OS - Windows 10 (x64)
LR version - CC (newest at the moment of writing).
Midi2Lr Version - 3.1.0.4 (newest at the moment of writing).
Controller - X Touch Mini

**Comment by santta** [comment]
I have the same problem, on windows 10. after the appearance of LRcopy and LRpaste, it does not work in any version

**Comment by dawiefourie** [comment]
I have the same problem as t-r-u - Just upgraded from a version released in 2017 because of the new futures in LR - not supported by the prev version of Midi2Lr that was installed.  The new futures of LR (like texture) is working, but LRcopy and LRpaste are not working. (It worked on the prev version that was installed)  I also tried to delete the default profile as suggested elsewhere on this site.....it is not working.

OS - Windows 7 (x64)
LR version - Classic CC newest at the moment
Midi2Lr version - 3.1.0.4 newest at the moment
Controller - Akai Midimix

**Comment by t-r-u** [comment]
I hope this will be fixed in the next update. The LRcopy and LRpaste are really useful in my workflow. For now I have to do much more sync and manual edit...

**Comment by rsjaffe** [comment]
The next update will simplify the code for LRcopy and LRpaste and should eliminate most of the problems. In the meantime, you can map the keystrokes to a button using [Keyboard Shortcuts](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#keyboard-shortcuts).

**Comment by rsjaffe** [comment]
fixed in 3.2
