### ISSUE TITLE
MIDI2LR does not recognize relative encoder positions anymore

### ISSUE THREAD

**Issue by HuFux** [rsjaffe/MIDI2LR#460]
@rsjaffe 

**Describe the bug**
I have an Arturia Beatstep board, which has endless rotary encoders and therefore does not need a pickup mode, because the knobs act in relative mode and automatically pick up the parameter of each individual picture, allowing for a seamless edit.
But with V3.3.2.0 this has changed. The rotary knobs no longer pick up the parameters of each individual picture after switching between the pictures, but instead continue on the new picture with the value from the previous picture. Therefore there are sudden parameter jumps when rotating the knob the first time on a new picture. The knobs act like the behavior would be if you have limited rotary knobs set to "absolute mode" without pickup mode enabled.
In V3.3.1.0 everything is fine. Bug introduced in V3.3.2.0.

**To Reproduce**
1. Set Arturia Beatstep knobs to "Relative 2" mode
2. Set Arturia Beatstep knobs acceleration to "OFF"
3. Allocate "Brightness" to one rotary knob in MIDI2LR
4. Set "two's complements", resolution 127 to all rotary knobs in MIDI2LR
5. Take two pictures, each of them with brightness set to 0
6. Correct brightness of first picture via the knob to -4.0
7. Switch to the second picture
8. Move the knob just a little bit and the brightness will jump from 0 to -4.1 instantly

-> Knob is acting like "absolute" mode, despite of setting "two's complement"

Bug is present in V3.3.2.0
Bug is NOT present in V3.3.1.0

**Expected behavior**
I would have expected, that the brightness of the second picture would not instantly jump to -4.1. Instead the brightness slider should start to move at its current position. So I would have expected that it would move to -0.1 instead.

**Screenshots**
- not needed -

**System(please complete the following information):**
 - OS: Windows 10 Pro 64 bit
 - Lightroom version 6.14
 - MIDI2LR version 3.3.2.0

**Additional context**
If you need more information or a tester to test a bug-fix, please contact me any time. Thanks

**Comment by rsjaffe** [comment]
Just tested latest version and it works as expected for all relative value types. No action needed.

**Comment by TheDude-hr** [comment]
Hi rsjaffe,

Same problem with the same midi controller .
I confirm that this bug seems to be introduced with version 3.3.2.0. Everything is working fine with 3.3.1.0.
To complete HuFux post : 

**To Reproduce :** 

- Arturia Beatstep knobs to "Relative 2" mode
- Arturia Beatstep knobs acceleration to "OFF"
- "two's complements", resolution 127 to all rotary knobs in MIDI2LR
- Correct a setting via the knob
- Move slider of the same setting with mouse
- Correct the same setting via the knob

--> the setting move from value previously set by knob and not by mouse.

**_Expected behavior (as in 3.3..1.0) :_** 

--> the setting move from value previously set by mouse.

**System :**

Windows 10 Pro 1909 64 bit
Lightroom version 9.0
MIDI2LR version 3.3.2.0 and 3.4.2.1

**Comment by HuFux** [comment]
Just tested latest version also on a different PC and it does still not work as expexted for all relative value types. Thanks TheDude-hr for third party confirmation. Action is definitely needed. Wirklich !

**Comment by NKame** [comment]
Nice to see it documented, now I know to which version I should revert to :-)
