### ISSUE TITLE
Glitch in config export?

### ISSUE THREAD

**Issue by sys3175** [rsjaffe/MIDI2LR#495]
Hi, while reverse engineering your configuration export file, I found that the first hotkey export is different from the others.

Keys={
{alt=false,shift=false,key="j",control=false},
{alt=false,key="l",control=false,command=false,shift=false},
...
as you can see, the order differs and the command key setting is not saved.
(I tried to programatically generate the config file and the import fails if I produce all the key entries uniformly in a loop).

Thank you for providing this great utility.  Adobe should hire you ;-) I think many people are staying with LR only because of the ease-of-use that you're giving us.

**Comment by rsjaffe** [comment]
Can you post the file that fails import? The missing command only means that the value is nil, so I assume you're using a windows PC. I'm using a serialization library to produce the export/import, and there is nothing in the code that treats the first hotkey differently from the rest. The order within the curly brackets doesn't matter: it's a matrix of key-value pairs. I will change the code to ensure that command gets set to false instead of nil.

**Comment by sys3175** [comment]
Ok, it turns out that this difference was a red herring (sorry for that), my first attempt had a comma missing in the profile list, which I got right in the 2nd try. So the file loads either way, with the shortened 1st key line or the full one like the 2nd line above.
So, no need to change the code, everything works fine, I just was under the impression that there might arise problems if not all values are exported.

**Comment by rsjaffe** [comment]
Lua treats nil (missing values) like false in most circumstances, so missing values are not an issue in this instance, but I will set it to false if missing just to make things more consistent.
