### ISSUE TITLE
Adjust CC settings, such as Resolution, are not being saved (or associated) with profile xml

### ISSUE THREAD

**Issue by onegrasshopper** [rsjaffe/MIDI2LR#607]
**Describe the bug**
Adjust CC settings, such as Resolution, are not being saved (or associated) with profile xml

**To Reproduce**
1) Set a relative CC knob to Exposure. "Adjust CC window" to: two's complement. Resolution 50.  Save profile as bigsteps.xml
2) Set the same relative CC slider to have Resolution 200. Call it smallsteps.xml
3) Loading profile bigsteps.xml from (1). Resolution is still 200.

**Expected behavior**
Loading the profile should load the associated "adjust cc" settings. 

**System(please complete the following information):**
 - OS: Win10
 - Lightroom version 11
 - MIDI2LR version 5.2

**Additional context**
looks like adjust cc settings are being saved as a generic "whole" in a separate settings.xml. This breaks any attempt to use profiles to change the resolution of a relative cc knob.

**Comment by rsjaffe** [comment]
Yes, that's by design. Several reasons:
1. People sharing profiles may be surprised by the results if they use a shared profile with controller settings
2. It adds another level of customization, and the program is already very complex: I hear complaints about that all the time
3. There are ways around this but it requires a decent amount of programming work, so it's not on my to-do list, as I don't think many people are looking for this (and there are some work-arounds).
4. For most people, having a single set of settings for the MIDI controls characteristics makes sense.

Suggestions:
1. Program one cc knob for small and one for large steps--use the profiles feature to map these to different sets of settings as needed
2. Fork MIDI2LR, enhance it by adding the feature you want (and a way for people to shut off the feature and use a single setting file), and file a pull request against the project. I'm quite happy to have contributors to the code.
