### ISSUE TITLE
Assertion failed: err == noErr

### ISSUE THREAD

**Issue by bighugs** [rsjaffe/MIDI2LR#65]
I'm getting this error with latest Lightroom CC and 10.10.5 using MIDI2LR_OSX_0.6.0

An internal error has occurred.

Assertion failed: err == noErr

Any ideas?

**Comment by mischnic** [comment]
Oh, I know what the problem is!

@rsjaffe You didn't package the .app correctly:

Current&Wrong structure:
MIDI2LR.lrplugin
|
---> About.lua
---> MIDI2LR.app
       |
       ---> MIDI2LR.app (the actual program)

Correct structure:
MIDI2LR.lrplugin
|
---> About.lua
---> MIDI2LR.app (the actual program)      

(Same error as in #45, because in both cases the plugin failed to launch the app. )

**Comment by rsjaffe** [comment]
Thanks. Fixed it.

**Comment by mischnic** [comment]
Yes, it starts correctly.

**Comment by rsjaffe** [comment]
Thanks for the feedback.
