### ISSUE TITLE
Error when profile assigned to masking

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#666]
**Describe the bug**
I'm getting the same "an internal error has occurred: ?:0: attempt to perform arithmetic on field '?" (a nil value) everytime I go into the masking tool (M) and midi2lr tries to load the file for "masking."
[MIDI2LR.log](https://github.com/rsjaffe/MIDI2LR/files/8962310/MIDI2LR.log)

There is no error if I leave the filename out of that box and leave it blank. I get the same error if I put anything in the box, regardless if it is a valid file, or missing file name.

**Comment by wunditta** [comment]
I found the bug after many hours. It is in FullRefresh and doprofilechange for 'direct' parameters (i.e. local adjustments). The line
`lrvalue = LrDevelopController.getValue(param)`
causes the issue, as "getValue" cannot return a value if no mask is selected. So changing the line in both functions to
`if LrDevelopController.getSelectedMask() then lrvalue = LrDevelopController.getValue(param) end`
avoids the error.

This may be a good opportunity to mention my branch [wunditta/MIDI2LR](https://github.com/wunditta/MIDI2LR) with some tweaks and new functions (e.g. new Lr functions added in recent updates). I did this unwillingly as I would prefer that only one distribution exists. But since the last update is some time ago, I do not know if and when this will be maintained.

I would greatly wish to be contacted to join my branch in this and could provide some resources for fixing bugs and smaller changes. I am not a professional programmer though. Therefore my possibilities are limited (as can be seen in my code).

**Comment by 153957** [comment]
Maybe create a Pull Request to merge your fork back into this project ( https://github.com/rsjaffe/MIDI2LR/pulls ). Who knows, perhaps it will be come active again, and it makes it easier for others to find your version and discuss the changes.

**Comment by wunditta** [comment]
Thanks for the hint. I am very new to github as well. Currently I am still actively developing and would like to reach a stable point for me before I will release my fork. Then I will create a pull request. However I have already documented all changes I did so far on the wiki page of my fork.

**Comment by wunditta** [comment]
There is a pre-release of my fork [wunditta/MIDI2LR](https://github.com/wunditta/MIDI2LR), so if someone is brave enough to test... ;-)
This and more or less all other issues here should be fixed.

**Comment by rsjaffe** [comment]
Fixed in https://github.com/rsjaffe/MIDI2LR/commit/d92e89addac1b8f0840dd39d44ecb9d592d9be67
